### PR TITLE
Revert "Fix Python 3.7 GenericMeta not found issue."

### PR DESCRIPTION
**Pull request by abatilo**
Reverts abatilo/sanic-swagger#7

cc @hairychris

It turns out that if I run the tests in Python 3.7, this doesn't work at all, lol.

### CODE REVIEW

**Comment by hairychris** [comment]
Are you sure? I'm using it right now on Python 3.7

What error are you getting?

**Comment by abatilo** [comment]
If you run the tests, some of the tests will fail on some of the other types from the typing module.

**Comment by hairychris** [comment]
These can be patched too most likely, why did the CI not pick up on this?

We either need to change the descriptors (says Python 3.7 support) or get this patched up fast. I'll go run the tests locally and see what I can do.

**Comment by abatilo** [comment]
I'm updating the descriptors right now, and I have created separate issues open (#12 and #15)

I guess I just assumed that the original fork was accurate with its descriptors, but I only ever tested on 3.6.

At the moment, CI only runs 3.6. I'll revert for now, and update the descriptors.

**Pull request merged**
